apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: {{ .Values.secret.mongodb.username }}
  mongo-root-password: {{ .Values.secret.mongodb.password }}
